apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-workload #workload name 
spec:
  replicas: 1 #number of pods
  selector:
    matchLabels:
      app: fastapi-workload #workload name 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fastapi-workload #workload name 
    spec:
      containers:
      - image: swr.ap-southeast-3.myhuaweicloud.com/moocfastapi/fastapi_deployment:v1.1
        imagePullPolicy: Always
        name: fastapi-container
      imagePullSecrets:
      - name: default-secret

---

apiVersion: v1
kind: Service  
metadata:
  name: fastapi-service 
  namespace: default
  labels:
    app: fastapi-workload #workload name 
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: 3000 #service port
      targetPort: 8080 #container port
      nodePort: 30000 # Node port
  selector:
    app: fastapi-workload #workload name 

  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

